# Generated by Django 5.2.7 on 2025-10-22 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EthicalAIGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Guideline title', max_length=200)),
                ('description', models.TextField(help_text='Detailed guideline description')),
                ('principle', models.CharField(help_text='Core ethical principle (e.g., Fairness, Transparency)', max_length=100)),
                ('implementation_details', models.TextField(help_text='How this guideline is implemented')),
                ('version', models.CharField(help_text='Guideline version', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether guideline is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ethical AI Guideline',
                'verbose_name_plural': 'Ethical AI Guidelines',
                'ordering': ['principle', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AIDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('screening', 'Application Screening'), ('matching', 'Job Matching'), ('ranking', 'Candidate Ranking'), ('recommendation', 'Recommendation')], max_length=20)),
                ('model_version', models.CharField(help_text='AI model version used', max_length=50)),
                ('input_data', models.JSONField(help_text='Input data used for decision (anonymized)')),
                ('output_data', models.JSONField(help_text='AI decision output')),
                ('confidence_score', models.FloatField(help_text='AI confidence in decision (0-1)')),
                ('explanation', models.TextField(help_text='Human-readable explanation of decision')),
                ('features_used', models.JSONField(default=list, help_text='Features/factors considered in decision')),
                ('human_reviewed', models.BooleanField(default=False, help_text='Whether decision was reviewed by human')),
                ('human_override', models.BooleanField(default=False, help_text='Whether human overrode AI decision')),
                ('override_reason', models.TextField(blank=True, help_text='Reason for human override')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_decisions', to='candidates.application')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_decisions_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Decision Log',
                'verbose_name_plural': 'AI Decision Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiasAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.CharField(choices=[('gender', 'Gender Bias Audit'), ('race', 'Racial Bias Audit'), ('age', 'Age Bias Audit'), ('location', 'Geographic Bias Audit'), ('education', 'Educational Background Bias Audit'), ('comprehensive', 'Comprehensive Bias Audit')], max_length=20)),
                ('audit_date', models.DateField(help_text='Date of audit')),
                ('model_version', models.CharField(help_text='AI model version audited', max_length=50)),
                ('sample_size', models.PositiveIntegerField(help_text='Number of decisions audited')),
                ('findings', models.TextField(help_text='Audit findings and observations')),
                ('bias_detected', models.BooleanField(default=False, help_text='Whether bias was detected')),
                ('bias_severity', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='none', max_length=20)),
                ('corrective_actions', models.TextField(blank=True, help_text='Corrective actions taken or planned')),
                ('metrics', models.JSONField(default=dict, help_text='Detailed audit metrics and statistics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bias_audits_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bias Audit Log',
                'verbose_name_plural': 'Bias Audit Logs',
                'ordering': ['-audit_date'],
            },
        ),
        migrations.CreateModel(
            name='DataPrivacyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('view', 'Data Viewed'), ('export', 'Data Exported'), ('delete', 'Data Deleted'), ('anonymize', 'Data Anonymized'), ('ai_training', 'Used in AI Training')], max_length=20)),
                ('data_type', models.CharField(help_text='Type of data accessed', max_length=100)),
                ('purpose', models.TextField(help_text='Purpose of data access')),
                ('consent_given', models.BooleanField(default=False, help_text='Whether user consent was obtained')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_accesses_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Privacy Log',
                'verbose_name_plural': 'Data Privacy Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
