# Generated by Django 5.2.7 on 2025-10-22 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name', max_length=200)),
                ('description', models.TextField(help_text='Company description')),
                ('website', models.URLField(blank=True, help_text='Company website')),
                ('logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='company_logos/')),
                ('industry', models.CharField(blank=True, help_text='Industry sector', max_length=100)),
                ('size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1001+', '1001+ employees')], help_text='Company size', max_length=50)),
                ('location', models.CharField(blank=True, help_text='Headquarters location', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=200)),
                ('description', models.TextField(help_text='Detailed job description')),
                ('responsibilities', models.TextField(help_text='Key responsibilities')),
                ('requirements', models.TextField(help_text='Required qualifications and skills')),
                ('preferred_qualifications', models.TextField(blank=True, help_text='Preferred qualifications (nice to have)')),
                ('location', models.CharField(help_text='Job location', max_length=200)),
                ('remote_type', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], default='onsite', max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary (transparency required)', max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary (transparency required)', max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR, GBP)', max_length=3)),
                ('benefits', models.TextField(blank=True, help_text='Benefits and perks')),
                ('skills_required', models.JSONField(default=list, help_text='Required skills list')),
                ('skills_preferred', models.JSONField(blank=True, default=list, help_text='Preferred skills list')),
                ('experience_min', models.PositiveIntegerField(default=0, help_text='Minimum years of experience')),
                ('experience_max', models.PositiveIntegerField(blank=True, help_text='Maximum years of experience', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('application_deadline', models.DateField(blank=True, help_text='Application deadline', null=True)),
                ('requires_cover_letter', models.BooleanField(default=True, help_text='Require personalized cover letter')),
                ('custom_questions', models.JSONField(blank=True, default=list, help_text='Custom application questions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='jobs.company')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-created_at'],
            },
        ),
    ]
