# Generated by Django 5.2.7 on 2025-10-22 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('screening', 'Screening Feedback'), ('interview', 'Interview Feedback'), ('technical', 'Technical Assessment Feedback'), ('final', 'Final Decision Feedback')], max_length=20)),
                ('strengths', models.TextField(help_text='Specific strengths observed (required for personalization)')),
                ('areas_for_improvement', models.TextField(help_text='Specific areas for growth (required for personalization)')),
                ('detailed_comments', models.TextField(help_text='Detailed, personalized feedback (required)')),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Rating (1-5)', null=True)),
                ('next_steps', models.TextField(blank=True, help_text='Information about next steps in the process')),
                ('is_visible_to_candidate', models.BooleanField(default=True, help_text='Make feedback visible to candidate immediately')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='candidates.application')),
                ('provided_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Feedback',
                'verbose_name_plural': 'Application Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(help_text='Candidate response to feedback')),
                ('is_public', models.BooleanField(default=False, help_text='Share anonymously with community for learning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.applicationfeedback')),
            ],
            options={
                'verbose_name': 'Feedback Response',
                'verbose_name_plural': 'Feedback Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('feedback_type', models.CharField(choices=[('screening', 'Screening Feedback'), ('interview', 'Interview Feedback'), ('technical', 'Technical Assessment Feedback'), ('final', 'Final Decision Feedback')], max_length=20)),
                ('strengths_template', models.TextField(help_text='Template for strengths section (must be customized)')),
                ('improvement_template', models.TextField(help_text='Template for areas of improvement (must be customized)')),
                ('comments_template', models.TextField(help_text='Template for detailed comments (must be customized)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Template',
                'verbose_name_plural': 'Feedback Templates',
                'ordering': ['name'],
            },
        ),
    ]
