# Generated by Django 5.2.7 on 2025-10-22 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, help_text='Upload your resume (PDF, DOC, DOCX)', null=True, upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, help_text='Default cover letter')),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Total years of professional experience')),
                ('current_title', models.CharField(blank=True, help_text='Current job title', max_length=200)),
                ('current_company', models.CharField(blank=True, help_text='Current employer', max_length=200)),
                ('salary_expectation_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary expectation', max_digits=10, null=True)),
                ('salary_expectation_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary expectation', max_digits=10, null=True)),
                ('preferred_locations', models.JSONField(blank=True, default=list, help_text='List of preferred work locations')),
                ('remote_preference', models.CharField(choices=[('remote', 'Remote Only'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('flexible', 'Flexible')], default='flexible', help_text='Work location preference', max_length=20)),
                ('availability_date', models.DateField(blank=True, help_text='Date available to start', null=True)),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of skills')),
                ('languages', models.JSONField(blank=True, default=list, help_text='Languages spoken with proficiency levels')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='Professional certifications')),
                ('education', models.JSONField(blank=True, default=list, help_text='Educational background')),
                ('work_authorization', models.CharField(blank=True, help_text='Work authorization status', max_length=100)),
                ('willing_to_relocate', models.BooleanField(default=False, help_text='Willing to relocate for the right opportunity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate Profile',
                'verbose_name_plural': 'Candidate Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('screening', 'Screening'), ('interviewing', 'Interviewing'), ('offer', 'Offer Extended'), ('accepted', 'Offer Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('cover_letter', models.TextField(help_text='Personalized cover letter for this application')),
                ('resume', models.FileField(blank=True, help_text='Custom resume for this application', null=True, upload_to='application_resumes/')),
                ('additional_documents', models.JSONField(blank=True, default=list, help_text='Additional documents attached to application')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the application was submitted', null=True)),
                ('last_status_change', models.DateTimeField(auto_now=True, help_text='Last time status was updated')),
                ('ai_match_score', models.FloatField(blank=True, help_text='AI-calculated match score (transparent to candidate)', null=True)),
                ('ai_match_explanation', models.TextField(blank=True, help_text='Explanation of AI match score (ethical AI)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobposting')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-submitted_at'],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
